server:
  port: 8888

app:
  api-prefix: /api

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
            - Path=/api/identity/**
          filters:
            - StripPrefix=1
        - id: profile_service
          uri: http://localhost:8081
          predicates:
            - Path=/api/profile/users/**
          filters:
            - StripPrefix=1